# set runtime dir
export XDG_RUNTIME_DIR=/var/run/user/`id -u`


# source aliases file
source $HOME/.config/zsh/aliases

# autocd into typed dir
setopt autocd

# enable autocolors
autoload -U colors && colors

# change colors for prompt etc.
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#777c66'

export TASKRC=~/Sync/Taskwarrior/taskrc
export TASKDATA=~/Sync/Taskwarrior/data
export TERM=xterm
# disable termfreeze on ctrl-s
stty stop undef

# move .zcompdump dir
autoload -Uz compinit
mkdir -p $HOME/.cache/zsh
compinit -d $HOME/.cache/zsh/zcompdump-$ZSH_VERSION

# add ctrl+a and ctrl+e support
bindkey -M viins '^a' beginning-of-line
bindkey -M viins '^e' end-of-line
bindkey '^[[1;5D' backward-word   # Ctrl+Left
bindkey '^[[1;5C' forward-word    # Ctrl+Right

# configure shell history
HISTFILE=$HOME/.cache/zsh/histfile.txt
HISTSIZE=10000
SAVEHIST=10000

# adding locations to PATH
export PATH="$HOME/.local/scripts:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/opt/texlive/2023/bin/x86_64-linux:$PATH"


# adding flatpak support
export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS"

# import plugins
source $HOME/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source $HOME/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source $HOME/.config/zsh/plugins/gitfast/gitfast.plugin.zsh


